app/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from app import db, login
from datetime import datetime


class Admin(db.Model):

    __tablename__ = "admins"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def __repr__(self):
        return 'Admin: {}\nUser ID: {}'.format(self.id, self.user_id)

    
class Secretary(db.Model):

    __tablename__ = "secretaries"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    consult_id = db.Column(db.Integer, db.ForeignKey('consults.id'))

    def __repr__(self):
        return 'Secretary: {}'.format(self.id)


class User(UserMixin, db.Model):

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(60), index=True, unique=True)
    login = db.Column(db.String(60), index=True, unique=True)
    full_name = db.Column(db.String(50), index=True)
    password = db.Column(db.String(128))
    admins = db.relationship('Admin', backref='user', lazy='dynamic')
    secretaries = db.relationship('Secretary', backref='user', lazy='dynamic')

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password, password)

    def __repr__(self):
        return 'User ID: {}\nUser Name: {}'.format(self.id, self.full_name)


@login.user_loader
def load_user(id):
    return User.query.get(int(id))


class Consult(db.Model):

    __tablename__ = "consults"

    id = db.Column(db.Integer, primary_key=True)
    consult_date = db.Column(db.DateTime, default=datetime.utcnow) 
    secretaries = db.relationship('Secretary', backref='consult', lazy='dynamic')
    doctors = db.relationship('Doctor', backref='consult', lazy='dynamic')
    id_patient = db.Column(db.Integer, db.ForeignKey('patients.id'))
    id_status_consult = db.Column(db.Integer, db.ForeignKey('status_consults.id'))

    def __repr__(self):
        return 'Consult ID: {}\nConsult date: {}\nPatient: {}\nStatus Consult: {}'.format(self.id,
                                                                                          self.consult_date,
                                                                                          self.id_patient,
                                                                                          self.id_status_consult)


class StatusConsult(db.Model):

    __tablename__ = "status_consults"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30), index=True)
    consults = db.relationship('Consult', backref='status_consult', lazy='dynamic')

    def __repr__(self):
        return 'StatusConsult ID: {}\nStatus: {}'.format(self.id, self.status)


class Doctor(db.Model):
    
    __tablename__ = 'doctors'

    id = db.Column(db.Integer, primary_key=True)
    full_name = db.Column(db.String(50), index=True)
    id_consult = db.Column(db.Integer, db.ForeignKey('consults.id'))
    id_specialty = db.Column(db.Integer, db.ForeignKey('specialties.id'))

    def __repr__(self):
        return 'Doctor ID: {}\nDoctor Name: {}'.format(self.id, self.full_name)


class OccupationArea(db.Model):

    __tablename__ = 'occupation_areas'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Integer, index=True)
    id_specialty = db.Column(db.Integer, db.ForeignKey('specialties.id'))

    def __repr__(self):
        return 'OccupationArea ID: {}\nOccupation: {}'.format(self.id, self.name)


class Specialty(db.Model):

    __tablename__ = 'specialties'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Integer, index=True)
    doctors = db.relationship('Doctor', backref='doctors_specialty', lazy="dynamic")
    occupation_areas = db.relationship('OccupationArea', backref='occupation_areas_specialties', lazy="dynamic")

    def __repr__(self):
        return 'Specialty ID: {}\nSpecialty: {}'.format(self.id, self.name)


class Patient(db.Model):
    
    __tablename__ = 'patients'
    
    id = db.Column(db.Integer, primary_key=True)
    consults = db.relationship('Consult', backref="patient", lazy="dynamic")

    def __repr__(self):
        return 'Patient ID: {}\nPatient Name: {}'.format(self.id, self.full_name)

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy 
from flask_migrate import Migrate
from flask_login import LoginManager 
from flask_bootstrap import Bootstrap 


db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_message = "Você deve fazer login para acessar esta página"
login.login_view = "auth.login"
bootstrap = Bootstrap()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    bootstrap.init_app(app)

    from app.admin import admin as admin_blueprint

    app.register_blueprint(admin_blueprint, url_prefix="/admin")

    from app.auth import auth as auth_blueprint

    app.register_blueprint(auth_blueprint)

    from app.main import main as main_blueprint

    app.register_blueprint(main_blueprint)

    return app

app/admin/__init__.py
from flask import Blueprint

admin =  Blueprint("admin", __name__)

from . import views

app/main/__init__.py
from flask import Blueprint

main =  Blueprint("main", __name__)

from . import views

app/main/views.py
from flask import render_template
from . import main


@main.route("/")
def homepage():
    return render_template("home/index.html", title="Bem vindo!")
    

app/templates/base.html
<!DOCTYPE html>
<html lang="pt_br">
    <head>
        <title>{{ title }} | Medplus</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/font-awesome.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
        <link rel="shortcut icon" href="{{ url_for('static', filename='img/plus.jpeg') }}">
    </head>

    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top topnav" role="navigation">

            <div class="container topnav">

                <div class="navbar-header">

                    <button type="button" class="navbar-toggle" date-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    
                        <span class="sr-only">Navegação</span>

                        <span id="icon-bar"></span>

                        <span id="icon-bar"></span>

                        <span id="icon-bar"></span>

                    </button>

                    <a class="navbar-brand topnav" href="{{ url_for('main.homepage') }}"><i class="fa fa-plus"></i> Medplus</a>

                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    
                    <ul class="nav navbar-nav navbar-right">

                        {% if current_user.is_anonymous %}

                            <li><a href="{{ url_for('auth.login') }}"><i class="fa fa-sign-in"></i> Login</a></li>
                        
                            <li><a href="{{ url_for('auth.register') }}"><i class="fa fa-plus"></i> Cadastrar</a></li>
                        {% endif %}
                    </ul>

                </div>

            </div>

        </nav>

        <div class="wrapper">

            {% block body %}{% endblock%}

        </div>

        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

        <script type="text/javascript" src=" {{ url_for('static', filename='css/bootstrap.min.css') }}"></script>

    </body>

</html>

app/templates/home/index.html
{% extends "base.html" %}
{% block tittle %}Home{% endblock %}
{% block body %}
<div class="intro-header">

    <div class="container">

        <div class="row">

            <div class="col-lg-12">

                <div class="intro-message">

                    <h1>MedPlus</h1>

                </div>

            </div>

        </div>

    </div>

</div>
<style>
    body {
      background: url('static/img/intro-bg.jpg') no-repeat center center fixed;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      background-size: cover;
      -o-background-size: cover;
      background-color:rgba(0, 0, 0, 0.1);
    }
    </style>
{% endblock%}